site_name: HSC
theme:
  name: material
  palette:
    - scheme: default
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: material/weather-night
        name: Dark mode
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      toggle:
        icon: material/weather-sunny
        name: Light mode

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - tables
  - toc:
      permalink: true

  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.betterem
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Úvod: index.md
  - 1. Jazyk C - Jednoduché datové typy, reprezentace signed a unsigned, dvojkový doplněk, floating point: HSC_1.md
  - 2. Jazyk C - Pole, vícerozměrná pole, ukazatele, generický ukazatel, řetězce: HSC_2.md
  - 3. Jazyk C - Operátory, funkce, návratové hodnoty, zásobník, ukazatele na funkce, standartní knihovny, direktivy: HSC_3.md
  - 4. Embedded systémy, základní charakteristika, typické součásti embedded systémů, ES v ASIC vs FPGA: HSC_4.md
  - 5. Architektonické koncepty počítače, ISA procesoru s příklady (stack, ACC, GPR), instrukční cyklus, RISC vs CISC, současné trendy CPU: HSC_5.md
  - 6. Zynq PS: HSC_6.md
  - 7. Microblaze – charakteristika a architektura CPU, možnosti konfigurace, možnosti cache: HSC_7.md
  - 8. Základní IP jádra s návazností na HW FPGA, obvody hodin, čítače/časovače, GPIO: HSC_8.md
  - 9. Sériové sběrnice - přehled a principy (SPI, IIC, UART): HSC_9.md
  - 10. Způsoby obsluhy periferií, polling, interrupt, základní struktura ovladače s jednoduchým příkladem: HSC_10.md
  - 11. Klasifikace sběrnic v embedded systémech, pojmy master, slave, arbiter, transakce, burst, teoretická a reálná bandwidth, topologie: HSC_11.md
  - 12.  AMBA AXI - AXI stream – princip rozhraní, transakce, backpressure, přenos z více zdrojů: HSC_12.md
  - 13. AMBA AXI - AXI MM (lite) – parametry, kanály, transakce čtení a zápisu, rozdíl mezi AXI4 a AXI4-lite: HSC_13.md
  - 15. DMA řadič, scatter gather, ovladače, koherence dat, přehled dostupných IP: HSC_15.md
  - 16. Jazyk VHDL - knihovny, entita – porty a generické parametry, architektura – deklarační část, tělo, přehled paralelních příkazů, proces a citlivostní seznam: HSC_16.md
  - 17. VHDL - základní datové typy, knihovní typy, VHDL pro syntézu - způsoby efektivního popisu paměťových, aritmetických a řídících obvodů: HSC_17.md
  - 18. FPGA - Struktura a přehled zdrojů SLICE, vytváření multiplexorů a režimy LUT: HSC_18.md
  - 19. FPGA - Aritmetické obvody – realizace sčítaček, násobičky, specializované obvody, podpora datových typů: HSC_19.md
  - 20. Model Composer – Výhody a nevýhody oproti popisu HDL/HLS, bloky Gateway in, základní aritmetické bloky, podpora AXI stream: HSC_20.md
  - 21. HLS – výhody a nevýhody oproti popisu HDL/Model Composer, popis flow, zpracování základních prvků jazyka C do HW struktur, Interface AXI4: HSC_21.md