site_name: HSC
theme:
  name: material

nav:
  - Úvod: index.md
  - 3. Jazyk C - Operátory, funkce, návratové hodnoty, zásobník, ukazatele na funkce, standartní knihovny, direktivy: HSC_3.md
  - 9. Sériové sběrnice - přehled a principy (SPI, IIC, UART): HSC_9.md